<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Brads-MacBook-Air.local" ignored="0" name="Default test" tests="14" failures="1" timestamp="2021-10-25T11:04:18 SAST" time="131.802" errors="0">
  <testcase name="TC_001_PersonIdentification_Basic" time="8.737" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_002_PersonIdentification_Basic_Invalid_ID" time="5.124" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_003_PersonIdentification_Enhanced" time="6.766" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_004_PersonIdentification_Enhanced_Invalid_ID" time="4.779" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_005_PersonIdentificationComprehensiveWithMortalityInformation" time="5.649" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_006_PersonIdentificationComprehensiveWithMortalityInformation_Invalid_ID" time="4.877" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_007_PersonVerification_Risk_Rating_Low_IdentityNumber" time="7.659" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_008_PersonVerification_Risk_Rating_Low_IdentityNumber_Invalid_ID" time="4.761" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_009_PersonVerification_Risk_Rating_High_IdentityNumber" time="4.362" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_010_PersonVerificationRiskRatinghigh_Identitynumber_invalid_ID" time="2.545" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_011_PersonVerification_RiskRating_Low_Passport" time="3.723" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_012_PersonVerification_RiskRating_Low_Passport_Invalid_Passport" time="3.464" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_013_PersonVerification_RiskRating_High_Passport" time="54.193" classname="runner.PartyVerificationRestRunner"/>
  <testcase name="TC_014_PersonVerification_RiskRating_High_Passport_Invalid_passport" time="14.643" classname="runner.PartyVerificationRestRunner">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at runner.PartyVerificationRestRunner.TC_014_PersonVerification_RiskRating_High_Passport_Invalid_passport(PartyVerificationRestRunner.java:146)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_014_PersonVerification_RiskRating_High_Passport_Invalid_passport -->
</testsuite> <!-- Default test -->
