<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="17" total="18" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10113" started-at="2021-10-27T11:58:30 SAST" finished-at="2021-10-27T11:58:40 SAST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10113" started-at="2021-10-27T11:58:30 SAST" finished-at="2021-10-27T11:58:40 SAST">
      <class name="runner.PartyVerificationRestRunner">
        <test-method status="FAIL" signature="TC_021_PersonVerification_RiskRating_High_Passport_Invalid_Format()[pri:15, instance:runner.PartyVerificationRestRunner@3514a4c0]" name="TC_021_PersonVerification_RiskRating_High_Passport_Invalid_Format" duration-ms="9627" started-at="2021-10-27T11:58:30 SAST" finished-at="2021-10-27T11:58:40 SAST">
          <exception class="org.json.JSONException">
            <message>
              <![CDATA[JSONObject["Type"] not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.json.JSONException: JSONObject["Type"] not found.
at org.json.JSONObject.get(JSONObject.java:572)
at com.exergyRestApi.PartyVerification.TC_021.PersonVerification_RiskRating_High_Passport_Invalid_Format(TC_021.java:46)
at runner.PartyVerificationRestRunner.TC_021_PersonVerification_RiskRating_High_Passport_Invalid_Format(PartyVerificationRestRunner.java:178)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.json.JSONException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_021_PersonVerification_RiskRating_High_Passport_Invalid_Format -->
        <test-method status="PASS" signature="EndTests()[pri:0, instance:runner.PartyVerificationRestRunner@3514a4c0]" name="EndTests" is-config="true" duration-ms="407" started-at="2021-10-27T11:58:40 SAST" finished-at="2021-10-27T11:58:40 SAST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndTests -->
      </class> <!-- runner.PartyVerificationRestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
